import { cpus, arch, platform } from 'node:os';

import { formatPlan, indexesUsed, sharedBlocks } from './explain.js';
import type { LabConfig, TableCount } from './lab.js';
import type { ScenarioRun } from './runner.js';

export interface ReportContext {
  readonly config: LabConfig;
  readonly rowCounts: readonly TableCount[];
  readonly serverVersion: string;
  readonly pgliteVersion: string;
  readonly buildMs: number;
  readonly generatedAt: Date;
}

function ms(value: number): string {
  if (value >= 100) return value.toFixed(0);
  if (value >= 10) return value.toFixed(1);
  return value.toFixed(2);
}

function speedup(value: number): string {
  if (!Number.isFinite(value)) return 'n/a';
  return value >= 100 ? `${value.toFixed(0)}x` : `${value.toFixed(1)}x`;
}

function bytes(value: number): string {
  if (value >= 1024 * 1024) return `${(value / (1024 * 1024)).toFixed(1)} MB`;
  if (value >= 1024) return `${(value / 1024).toFixed(0)} kB`;
  return `${value} B`;
}

function markdownTable(headers: readonly string[], rows: readonly (readonly string[])[]): string {
  const lines = [
    `| ${headers.join(' | ')} |`,
    `| ${headers.map(() => '---').join(' | ')} |`,
    ...rows.map((r) => `| ${r.join(' | ')} |`),
  ];
  return lines.join('\n');
}

function fence(language: string, body: string): string {
  return ['```' + language, body, '```'].join('\n');
}

export function renderBenchmarkMarkdown(runs: readonly ScenarioRun[], ctx: ReportContext): string {
  const cpu = cpus()[0]?.model ?? 'unknown CPU';
  const out: string[] = [];

  out.push('# Benchmark results');
  out.push('');
  out.push(
    '<!-- Generated by `npm run bench`. Every number below came from the run described',
    '     under "Environment". Do not edit by hand: the next run overwrites it. -->',
  );
  out.push('');
  out.push(
    '> **This file is generated.** `npm run bench` rewrites it end to end. Absolute',
    '> milliseconds are a property of the machine that produced them; the ratios are',
    '> the part that travels.',
  );
  out.push('');

  out.push('## Environment');
  out.push('');
  out.push(
    markdownTable(
      ['Key', 'Value'],
      [
        ['Generated', ctx.generatedAt.toISOString()],
        ['Engine', ctx.serverVersion],
        ['PGlite', ctx.pgliteVersion],
        ['Node', process.version],
        ['Platform', `${platform()} ${arch()}`],
        ['CPU', cpu],
        ['Scale', String(ctx.config.scale)],
        ['Seed', String(ctx.config.seed)],
        ['Schema + seed + analyze', `${ms(ctx.buildMs)} ms`],
      ],
    ),
  );
  out.push('');
  out.push('Dataset:');
  out.push('');
  out.push(
    markdownTable(
      ['Table', 'Rows'],
      ctx.rowCounts.map((c) => [`\`${c.table}\``, c.rows.toLocaleString('en-US')]),
    ),
  );
  out.push('');

  out.push('## Results');
  out.push('');
  out.push(
    markdownTable(
      ['#', 'Scenario', 'Technique', 'Naive', 'Optimized', 'Speedup', 'Rows'],
      runs.map((run) => [
        `[${run.scenario.id.slice(0, 2)}](sql/scenarios/${run.scenario.id}/)`,
        run.scenario.title,
        run.scenario.technique,
        `${ms(run.naive.timing.medianMs)} ms`,
        `${ms(run.optimized.timing.medianMs)} ms`,
        `**${speedup(run.speedup)}**`,
        run.comparison.equal ? String(run.comparison.rowCount) : 'MISMATCH',
      ]),
    ),
  );
  out.push('');
  out.push(
    'Each figure is the median of several timed runs after a discarded warmup; the ' +
      'exact iteration count per scenario is in its `meta.json`. Both queries in a ' +
      'row return the same rows, and the harness fails the run if they do not.',
  );
  out.push('');

  out.push('## Detail');
  out.push('');
  for (const run of runs) {
    out.push(`### ${run.scenario.id}`);
    out.push('');
    out.push(`**${run.scenario.title}** — ${run.scenario.summary}`);
    out.push('');
    out.push(
      `[Scenario notes and SQL](sql/scenarios/${run.scenario.id}/) · ` +
        `naive **${ms(run.naive.timing.medianMs)} ms** → ` +
        `optimized **${ms(run.optimized.timing.medianMs)} ms** ` +
        `(**${speedup(run.speedup)}**, ${run.comparison.equal ? `${run.comparison.rowCount} rows, verified identical` : 'ROW MISMATCH'})`,
    );
    out.push('');

    const naiveBlocks = sharedBlocks(run.naive.explain.Plan);
    const optimizedBlocks = sharedBlocks(run.optimized.explain.Plan);
    out.push(
      markdownTable(
        ['', 'Median', 'Min', 'Max', 'Buffers (8 kB pages)', 'Indexes used'],
        [
          [
            'naive',
            `${ms(run.naive.timing.medianMs)} ms`,
            `${ms(run.naive.timing.minMs)} ms`,
            `${ms(run.naive.timing.maxMs)} ms`,
            naiveBlocks.toLocaleString('en-US'),
            indexesUsed(run.naive.explain.Plan)
              .map((i) => `\`${i}\``)
              .join(', ') || '—',
          ],
          [
            'optimized',
            `${ms(run.optimized.timing.medianMs)} ms`,
            `${ms(run.optimized.timing.minMs)} ms`,
            `${ms(run.optimized.timing.maxMs)} ms`,
            optimizedBlocks.toLocaleString('en-US'),
            indexesUsed(run.optimized.explain.Plan)
              .map((i) => `\`${i}\``)
              .join(', ') || '—',
          ],
        ],
      ),
    );
    out.push('');

    if (run.createdObjects.length > 0) {
      out.push('Objects the fix creates:');
      out.push('');
      out.push(
        markdownTable(
          ['Object', 'Kind', 'Size'],
          run.createdObjects.map((o) => [`\`${o.name}\``, kindLabel(o.kind), bytes(o.bytes)]),
        ),
      );
      out.push('');
    }

    const notes = run.notes;
    if (notes !== undefined && notes.rows.length > 0) {
      out.push(
        markdownTable(
          notes.fields,
          notes.rows.map((row) => notes.fields.map((f) => formatCell(row[f]))),
        ),
      );
      out.push('');
    }

    out.push('<details>');
    out.push('<summary>Plans</summary>');
    out.push('');
    out.push('Naive:');
    out.push('');
    out.push(fence('sql', run.naive.sql));
    out.push('');
    out.push(fence('text', formatPlan(run.naive.explain)));
    out.push('');
    out.push('Optimized:');
    out.push('');
    out.push(fence('sql', run.optimized.sql));
    out.push('');
    out.push(fence('text', formatPlan(run.optimized.explain)));
    out.push('');
    out.push('</details>');
    out.push('');
  }

  return out.join('\n').replace(/\n{3,}/g, '\n\n').trimEnd() + '\n';
}

function kindLabel(kind: string): string {
  switch (kind) {
    case 'r':
      return 'table';
    case 'i':
      return 'index';
    case 'm':
      return 'materialized view';
    case 'v':
      return 'view';
    case 'S':
      return 'sequence';
    case 'p':
      return 'partitioned table';
    default:
      return kind;
  }
}

function formatCell(value: unknown): string {
  if (value === null || value === undefined) return '-';
  if (value instanceof Date) return value.toISOString();
  if (typeof value === 'object') return JSON.stringify(value);
  // eslint-disable-next-line @typescript-eslint/no-base-to-string -- objects are handled above
  return String(value);
}
